In [705]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import folium
import re

In [706]:
# 1. Global charging stations
global_stations = pd.read_csv('../Data/charging_station.csv')
global_stations.head()

,id,name,city,state_province,country_code,latitude,longitude,ports,power_kw,power_class,is_fast_dc
0,307660,Av. de Tarragona,Andorra,UNKNOWN,AD,42.505254,1.528861,10,300.0,DC_ULTRA_(>=150kW),True
1,301207,Parquing Costa Rodona,Encamp,UNKNOWN,AD,42.537213,1.727014,10,22.0,AC_HIGH_(22-49kW),False
2,301206,Hotel Naudi,Unknown City,UNKNOWN,AD,42.576811,1.666061,1,11.0,AC_L2_(7.5-21kW),False
3,301205,Hotel Piolets Soldeu Centre,Unknown City,UNKNOWN,AD,42.576466,1.667317,1,22.0,AC_HIGH_(22-49kW),False
4,301204,Hotel Serras,Unknown City,UNKNOWN,AD,42.579458,1.659215,3,11.0,AC_L2_(7.5-21kW),False

In [707]:
global_stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242417 entries, 0 to 242416
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              242417 non-null  int64
 1   name            242417 non-null  object
 2   city            242417 non-null  object
 3   state_province  242417 non-null  object
 4   country_code    242417 non-null  object
 5   latitude        242417 non-null  float64
 6   longitude       242417 non-null  float64
 7   ports           242417 non-null  int64
 8   power_kw        237757 non-null  float64
 9   power_class     242417 non-null  object
 10  is_fast_dc      242417 non-null  bool
dtypes: bool(1), float64(3), int64(2), object(5)
memory usage: 18.7+ MB

In [708]:
global_stations['country_code'].unique()

array(['AD', 'AE', 'AF', 'AL', 'AM', 'AR', 'AT', 'AU', 'AX', 'AZ', 'BA',
       'BB', 'BE', 'BG', 'BH', 'BR', 'BW', 'BY', 'CA', 'CH', 'CL', 'CN',
       'CO', 'CR', 'CY', 'CZ', 'DE', 'DK', 'DO', 'EC', 'EE', 'EG', 'ES',
       'ET', 'FI', 'FO', 'FR', 'GB', 'GE', 'GG', 'GH', 'GI', 'GR', 'GT',
       'HK', 'HR', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IQ', 'IS', 'IT',
       'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KR', 'KZ', 'LI', 'LK',
       'LT', 'LU', 'LV', 'MA', 'MC', 'MD', 'ME', 'MK', 'MM', 'MO', 'MT',
       'MX', 'MY', 'NAM', 'NL', 'NO', 'NP', 'NZ', 'OM', 'PA', 'PE', 'PH',
       'PK', 'PL', 'PR', 'PS', 'PT', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU',
       'RW', 'SA', 'SE', 'SG', 'SI', 'SJ', 'SK', 'SM', 'SZ', 'TH', 'TN',
       'TR', 'TT', 'TW', 'UA', 'UG', 'US', 'UY', 'UZ', 'VN', 'XK', 'ZA'],
      dtype=object)

In [709]:
kenya_global = global_stations[global_stations['country_code'] == 'KE']
kenya_global

,id,name,city,state_province,country_code,latitude,longitude,ports,power_kw,power_class,is_fast_dc
128395,267507,City Mall EvChaja,Unknown City,Mombasa,KE,-4.020064,39.720491,1,22.0,AC_HIGH_(22-49kW),False
128396,267505,Waiyaki Way,Unknown City,Nairobi,KE,-1.259614,36.776883,1,22.0,AC_HIGH_(22-49kW),False
128397,194150,Waterfront Mall EvChaja,Unknown City,Nairobi,KE,-1.329425,36.715820,1,22.0,AC_HIGH_(22-49kW),False
128398,194149,Two Rivers Mall EvChaja,Gachie,Nairobi,KE,-1.210229,36.795216,1,11.0,AC_L2_(7.5-21kW),False
128399,189881,Nopea Ride Village Market,Nairobi,Nairobi,KE,-1.227277,36.805228,1,22.0,AC_HIGH_(22-49kW),False
128400,189880,Nopea JKIA Airport,Nairobi,Nairobi,KE,-1.333731,36.928334,1,22.0,AC_HIGH_(22-49kW),False
128401,175802,Two Rivers Mall Nairobi (Nopea),Nairobi,Nairobi,KE,-1.211449,36.795808,1,11.0,AC_L2_(7.5-21kW),False
128402,175801,Sarit Centre Nairobi,Nairobi,Nairobi,KE,-1.261245,36.802243,1,22.0,AC_HIGH_(22-49kW),False
128403,175800,TRM Mall,Nairobi,Nairobi,KE,-1.219824,36.889224,2,22.0,AC_HIGH_(22-49kW),False
128404,175799,Holy Family Basilica Parking Silo,Nairobi,Nairobi,KE,-1.287358,36.820061,1,11.0,AC_L2_(7.5-21kW),False
128405,175798,The Hub Mall Karen,Mutuini,Nairobi,KE,-1.319503,36.703528,1,11.0,AC_L2_(7.5-21kW),False
128406,94957,Knights Energy,Nairobi,Nairobi,KE,-1.340858,36.757547,3,3.6,AC_L1_(<7.5kW),False

In [710]:
kenya_global.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 128395 to 128406
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              12 non-null     int64
 1   name            12 non-null     object
 2   city            12 non-null     object
 3   state_province  12 non-null     object
 4   country_code    12 non-null     object
 5   latitude        12 non-null     float64
 6   longitude       12 non-null     float64
 7   ports           12 non-null     int64
 8   power_kw        12 non-null     float64
 9   power_class     12 non-null     object
 10  is_fast_dc      12 non-null     bool
dtypes: bool(1), float64(3), int64(2), object(5)
memory usage: 1.0+ KB

In [711]:
# 2. Kenyan EV charging stations sample
kenya_stations_sample = pd.read_csv('../Data/kenya_ev_charging_stations_sample.csv')
kenya_stations_sample.head()

,County/City,Station Name,Charger Type,Connector Types,Latitude,Longitude
0,Nairobi,Sarit Centre,AC + DC,"Type2, CHAdeMO",-1.261245,36.802243
1,Nairobi,Two Rivers Mall,AC,Type2,-1.210229,36.795216
2,Nairobi,Village Market Gigiri,AC,Type2,-1.227277,36.805228
3,Nairobi,UNGA House Westlands,AC,Type2,-1.262890,36.804670
4,Nairobi,KCB Towers Upper Hill,AC,Type2,-1.301320,36.812790

In [712]:
kenya_stations_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   County/City      16 non-null     object
 1   Station Name     16 non-null     object
 2   Charger Type     16 non-null     object
 3   Connector Types  16 non-null     object
 4   Latitude         16 non-null     float64
 5   Longitude        16 non-null     float64
dtypes: float64(2), object(4)
memory usage: 896.0+ bytes

In [713]:
# 3. Kenya Population census data
population = pd.read_csv('../Data/kenya-population-distibution-2019-census.csv')
population.head()

       County       Total       Male     Female Intersex
0       KENYA  14,831,700  7,352,134  7,478,883      683
1     Mombasa   1,208,333    610,257    598,046       30
2       Kwale     126,431     62,395     64,031        5
3      Kilifi     393,888    191,324    202,558        6
4  Tana River      75,722     37,854     37,867        1

In [714]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   County    48 non-null     object
 1   Total     48 non-null     object
 2   Male      48 non-null     object
 3   Female    48 non-null     object
 4   Intersex  48 non-null     object
dtypes: object(5)
memory usage: 2.0+ KB

In [715]:
admin_boundaries = pd.read_excel("../Data/ken_adminboundaries_tabulardata.xlsx")
admin_boundaries.head()

,OBJECTID *,Shape *,admin2Name_en,admin2Pcode,admin2RefName,admin2AltName1_en,admin2AltName2_en,admin1Name_en,admin1Pcode,admin0Name_en,admin0Pcode,date,validOn,validTo,Shape_Length,Shape_Area
0,1,Polygon,Ainabkoi,KE027144,<Null>,<Null>,<Null>,Uasin Gishu,KE027,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.746986,0.040829
1,2,Polygon,Ainamoi,KE035190,<Null>,<Null>,<Null>,Kericho,KE035,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.917307,0.019957
2,3,Polygon,Aldai,KE029152,<Null>,<Null>,<Null>,Nandi,KE029,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.402637,0.038000
3,4,Polygon,Alego Usonga,KE041234,<Null>,<Null>,<Null>,Siaya,KE041,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.081354,0.049357
4,5,Polygon,Awendo,KE044254,<Null>,<Null>,<Null>,Migori,KE044,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.743915,0.021365

In [716]:
admin_boundaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OBJECTID *         290 non-null    int64
 1   Shape *            290 non-null    object
 2   admin2Name_en      290 non-null    object
 3   admin2Pcode        290 non-null    object
 4   admin2RefName      290 non-null    object
 5   admin2AltName1_en  290 non-null    object
 6   admin2AltName2_en  290 non-null    object
 7   admin1Name_en      290 non-null    object
 8   admin1Pcode        290 non-null    object
 9   admin0Name_en      290 non-null    object
 10  admin0Pcode        290 non-null    object
 11  date               290 non-null    datetime64[ns]
 12  validOn            290 non-null    datetime64[ns]
 13  validTo            290 non-null    object
 14  Shape_Length       290 non-null    float64
 15  Shape_Area         290 non-null    float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(11)
memory usage: 36.4+ KB

### Data Cleaning

In [717]:
kenya_global.duplicated().sum()

0

In [718]:
kenya_global.isnull().sum()

id                0
name              0
city              0
state_province    0
country_code      0
latitude          0
longitude         0
ports             0
power_kw          0
power_class       0
is_fast_dc        0
dtype: int64

In [719]:
kenya_stations_sample.duplicated().sum()

0

In [720]:
kenya_stations_sample.isnull().sum()

County/City        0
Station Name       0
Charger Type       0
Connector Types    0
Latitude           0
Longitude          0
dtype: int64

In [721]:
population.duplicated().sum()

0

In [722]:
population.isnull().sum()

County      0
Total       0
Male        0
Female      0
Intersex    0
dtype: int64

In [723]:
admin_boundaries.duplicated().sum()

0

In [724]:
admin_boundaries.isnull().sum()

OBJECTID *           0
Shape *              0
admin2Name_en        0
admin2Pcode          0
admin2RefName        0
admin2AltName1_en    0
admin2AltName2_en    0
admin1Name_en        0
admin1Pcode          0
admin0Name_en        0
admin0Pcode          0
date                 0
validOn              0
validTo              0
Shape_Length         0
Shape_Area           0
dtype: int64

### Data preparation

In [725]:
kenya_global.head()

,id,name,city,state_province,country_code,latitude,longitude,ports,power_kw,power_class,is_fast_dc
128395,267507,City Mall EvChaja,Unknown City,Mombasa,KE,-4.020064,39.720491,1,22.0,AC_HIGH_(22-49kW),False
128396,267505,Waiyaki Way,Unknown City,Nairobi,KE,-1.259614,36.776883,1,22.0,AC_HIGH_(22-49kW),False
128397,194150,Waterfront Mall EvChaja,Unknown City,Nairobi,KE,-1.329425,36.715820,1,22.0,AC_HIGH_(22-49kW),False
128398,194149,Two Rivers Mall EvChaja,Gachie,Nairobi,KE,-1.210229,36.795216,1,11.0,AC_L2_(7.5-21kW),False
128399,189881,Nopea Ride Village Market,Nairobi,Nairobi,KE,-1.227277,36.805228,1,22.0,AC_HIGH_(22-49kW),False

In [726]:
kenya_global = kenya_global.drop(columns=['id', 'city', 'is_fast_dc'])
kenya_global.head()

,name,state_province,country_code,latitude,longitude,ports,power_kw,power_class
128395,City Mall EvChaja,Mombasa,KE,-4.020064,39.720491,1,22.0,AC_HIGH_(22-49kW)
128396,Waiyaki Way,Nairobi,KE,-1.259614,36.776883,1,22.0,AC_HIGH_(22-49kW)
128397,Waterfront Mall EvChaja,Nairobi,KE,-1.329425,36.715820,1,22.0,AC_HIGH_(22-49kW)
128398,Two Rivers Mall EvChaja,Nairobi,KE,-1.210229,36.795216,1,11.0,AC_L2_(7.5-21kW)
128399,Nopea Ride Village Market,Nairobi,KE,-1.227277,36.805228,1,22.0,AC_HIGH_(22-49kW)

In [727]:
kenya_global = kenya_global.rename(columns={"state_province": "county", "name": "station name"})

In [728]:
kenya_global['county'].value_counts()

Nairobi    11
Mombasa     1
Name: county, dtype: int64

In [729]:
kenya_global["charger type"] = kenya_global["power_class"].str.split("_").str[0].str.upper()

In [730]:
kenya_global = kenya_global.drop(columns = ["power_class", "power_kw"])

In [731]:
kenya_global.head(2)

,station name,county,country_code,latitude,longitude,ports,charger type
128395,City Mall EvChaja,Mombasa,KE,-4.020064,39.720491,1,AC
128396,Waiyaki Way,Nairobi,KE,-1.259614,36.776883,1,AC

In [732]:
kenya_stations_sample.head()

,County/City,Station Name,Charger Type,Connector Types,Latitude,Longitude
0,Nairobi,Sarit Centre,AC + DC,"Type2, CHAdeMO",-1.261245,36.802243
1,Nairobi,Two Rivers Mall,AC,Type2,-1.210229,36.795216
2,Nairobi,Village Market Gigiri,AC,Type2,-1.227277,36.805228
3,Nairobi,UNGA House Westlands,AC,Type2,-1.262890,36.804670
4,Nairobi,KCB Towers Upper Hill,AC,Type2,-1.301320,36.812790

In [733]:
kenya_stations_sample =kenya_stations_sample.drop(columns='Connector Types')

In [734]:
kenya_stations_sample = kenya_stations_sample.rename(columns={"County/City": "county", "Station Name": "station name", "Charger Type": "charger type", "Latitude": "latitude", "Longitude": "longitude"})

In [735]:
kenya_stations_sample['county'].value_counts()

Nairobi     9
Mavoko      1
Nakuru      1
Mombasa     1
Narok       1
Kisumu      1
Kiambu      1
Naivasha    1
Name: county, dtype: int64

In [736]:
kenya_stations_sample['county'] = kenya_stations_sample['county'].replace(['Mavoko', 'Naivasha'], ['Machakos', 'Nakuru'])

In [737]:
kenya_stations_sample['county'].value_counts()

Nairobi     9
Nakuru      2
Mombasa     1
Kisumu      1
Kiambu      1
Narok       1
Machakos    1
Name: county, dtype: int64

In [738]:
kenya_stations_sample.head(2)

    county     station name charger type  latitude  longitude
0  Nairobi     Sarit Centre      AC + DC -1.261245  36.802243
1  Nairobi  Two Rivers Mall           AC -1.210229  36.795216

In [739]:
population.head()

       County       Total       Male     Female Intersex
0       KENYA  14,831,700  7,352,134  7,478,883      683
1     Mombasa   1,208,333    610,257    598,046       30
2       Kwale     126,431     62,395     64,031        5
3      Kilifi     393,888    191,324    202,558        6
4  Tana River      75,722     37,854     37,867        1

In [740]:
population = population.drop(columns=['Male', 'Female', 'Intersex'])

In [741]:
population = population.rename(columns={"County": "county", "Total": "population"})

In [742]:
population['population'] = population['population'].str.replace(',', '').astype(int)

In [743]:
admin_boundaries.head()

,OBJECTID *,Shape *,admin2Name_en,admin2Pcode,admin2RefName,admin2AltName1_en,admin2AltName2_en,admin1Name_en,admin1Pcode,admin0Name_en,admin0Pcode,date,validOn,validTo,Shape_Length,Shape_Area
0,1,Polygon,Ainabkoi,KE027144,<Null>,<Null>,<Null>,Uasin Gishu,KE027,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.746986,0.040829
1,2,Polygon,Ainamoi,KE035190,<Null>,<Null>,<Null>,Kericho,KE035,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.917307,0.019957
2,3,Polygon,Aldai,KE029152,<Null>,<Null>,<Null>,Nandi,KE029,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.402637,0.038000
3,4,Polygon,Alego Usonga,KE041234,<Null>,<Null>,<Null>,Siaya,KE041,Kenya,KE,2017-11-03,2018-06-07,<Null>,1.081354,0.049357
4,5,Polygon,Awendo,KE044254,<Null>,<Null>,<Null>,Migori,KE044,Kenya,KE,2017-11-03,2018-06-07,<Null>,0.743915,0.021365

In [744]:
admin_boundaries = admin_boundaries.rename(columns={"admin1Name_en": "county","admin2Name_en": "sub county", "admin0Pcode": "country code", "Shape_Area": "shape area", "Shape_Length": "shape length"})

In [745]:
admin_boundaries = admin_boundaries[['county', 'sub county', 'country code', 'shape area', 'shape length']]

In [746]:
admin_boundaries.head(2)

        county sub county country code  shape area  shape length
0  Uasin Gishu   Ainabkoi           KE    0.040829      1.746986
1      Kericho    Ainamoi           KE    0.019957      0.917307

merging all the stations from kenyaglobal and from kenya sations together

In [747]:
kenya_global.head(2)

,station name,county,country_code,latitude,longitude,ports,charger type
128395,City Mall EvChaja,Mombasa,KE,-4.020064,39.720491,1,AC
128396,Waiyaki Way,Nairobi,KE,-1.259614,36.776883,1,AC

In [748]:
kenya_stations_sample.head(2)

    county     station name charger type  latitude  longitude
0  Nairobi     Sarit Centre      AC + DC -1.261245  36.802243
1  Nairobi  Two Rivers Mall           AC -1.210229  36.795216

In [749]:
# Combine all rows from both dataframes
kenya_stations = pd.concat([kenya_global, kenya_stations_sample], ignore_index=True)
kenya_stations

,station name,county,country_code,latitude,longitude,ports,charger type
0,City Mall EvChaja,Mombasa,KE,-4.020064,39.720491,1.0,AC
1,Waiyaki Way,Nairobi,KE,-1.259614,36.776883,1.0,AC
2,Waterfront Mall EvChaja,Nairobi,KE,-1.329425,36.715820,1.0,AC
3,Two Rivers Mall EvChaja,Nairobi,KE,-1.210229,36.795216,1.0,AC
4,Nopea Ride Village Market,Nairobi,KE,-1.227277,36.805228,1.0,AC
5,Nopea JKIA Airport,Nairobi,KE,-1.333731,36.928334,1.0,AC
6,Two Rivers Mall Nairobi (Nopea),Nairobi,KE,-1.211449,36.795808,1.0,AC
7,Sarit Centre Nairobi,Nairobi,KE,-1.261245,36.802243,1.0,AC
8,TRM Mall,Nairobi,KE,-1.219824,36.889224,2.0,AC
9,Holy Family Basilica Parking Silo,Nairobi,KE,-1.287358,36.820061,1.0,AC
10,The Hub Mall Karen,Nairobi,KE,-1.319503,36.703528,1.0,AC
11,Knights Energy,Nairobi,KE,-1.340858,36.757547,3.0,AC
12,Sarit Centre,Nairobi,NaN,-1.261245,36.802243,NaN,AC + DC
13,Two Rivers Mall,Nairobi,NaN,-1.210229,36.795216,NaN,AC
14,Village Market Gigiri,Nairobi,NaN,-1.227277,36.805228,NaN,AC
15,UNGA House Westlands,Nairobi,NaN,-1.262890,36.804670,NaN,AC
16,KCB Towers Upper Hill,Nairobi,NaN,-1.301320,36.812790,NaN,AC
17,Britam Towers Upper Hill,Nairobi,NaN,-1.299760,36.813140,NaN,AC
18,Movenpick Westlands,Nairobi,NaN,-1.261070,36.804990,NaN,AC
19,Stima Plaza,Nairobi,NaN,-1.271410,36.820530,NaN,AC/DC
20,Ruaraka KPLC,Nairobi,NaN,-1.259280,36.859540,NaN,AC/DC
21,Westside Mall,Nakuru,NaN,-0.287090,36.063930,NaN,AC
22,Buffalo Mall,Nakuru,NaN,3.292720,37.204020,NaN,AC
23,Trinity Energy,Kiambu,NaN,-1.111340,36.784300,NaN,AC
24,Mega City Mall,Kisumu,NaN,-0.107230,34.770510,NaN,AC
25,City Mall Nyali,Mombasa,NaN,-4.020064,39.720491,NaN,AC
26,Dallas Lounge,Narok,NaN,-1.087500,35.877100,NaN,AC
27,Petrocity,Machakos,NaN,-1.428770,36.960850,NaN,AC + DC

In [750]:
kenya_stations = kenya_stations.drop(index=[12, 13, 14, 25])
kenya_stations

,station name,county,country_code,latitude,longitude,ports,charger type
0,City Mall EvChaja,Mombasa,KE,-4.020064,39.720491,1.0,AC
1,Waiyaki Way,Nairobi,KE,-1.259614,36.776883,1.0,AC
2,Waterfront Mall EvChaja,Nairobi,KE,-1.329425,36.715820,1.0,AC
3,Two Rivers Mall EvChaja,Nairobi,KE,-1.210229,36.795216,1.0,AC
4,Nopea Ride Village Market,Nairobi,KE,-1.227277,36.805228,1.0,AC
5,Nopea JKIA Airport,Nairobi,KE,-1.333731,36.928334,1.0,AC
6,Two Rivers Mall Nairobi (Nopea),Nairobi,KE,-1.211449,36.795808,1.0,AC
7,Sarit Centre Nairobi,Nairobi,KE,-1.261245,36.802243,1.0,AC
8,TRM Mall,Nairobi,KE,-1.219824,36.889224,2.0,AC
9,Holy Family Basilica Parking Silo,Nairobi,KE,-1.287358,36.820061,1.0,AC
10,The Hub Mall Karen,Nairobi,KE,-1.319503,36.703528,1.0,AC
11,Knights Energy,Nairobi,KE,-1.340858,36.757547,3.0,AC
15,UNGA House Westlands,Nairobi,NaN,-1.262890,36.804670,NaN,AC
16,KCB Towers Upper Hill,Nairobi,NaN,-1.301320,36.812790,NaN,AC
17,Britam Towers Upper Hill,Nairobi,NaN,-1.299760,36.813140,NaN,AC
18,Movenpick Westlands,Nairobi,NaN,-1.261070,36.804990,NaN,AC
19,Stima Plaza,Nairobi,NaN,-1.271410,36.820530,NaN,AC/DC
20,Ruaraka KPLC,Nairobi,NaN,-1.259280,36.859540,NaN,AC/DC
21,Westside Mall,Nakuru,NaN,-0.287090,36.063930,NaN,AC
22,Buffalo Mall,Nakuru,NaN,3.292720,37.204020,NaN,AC
23,Trinity Energy,Kiambu,NaN,-1.111340,36.784300,NaN,AC
24,Mega City Mall,Kisumu,NaN,-0.107230,34.770510,NaN,AC
26,Dallas Lounge,Narok,NaN,-1.087500,35.877100,NaN,AC
27,Petrocity,Machakos,NaN,-1.428770,36.960850,NaN,AC + DC